# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2f530e1438329317e9e832a31b48573c"
name = "shoptempl-rails-stimulus"
handle = "shoptempl-rails-stimulus"
application_url = "https://techrepublic-citizens-independence-samples.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tyghs-test-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://techrepublic-citizens-independence-samples.trycloudflare.com/auth/callback",
  "https://techrepublic-citizens-independence-samples.trycloudflare.com/auth/shopify/callback",
  "https://techrepublic-citizens-independence-samples.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app_uninstalled"

[pos]
embedded = false
